# Generated by Django 4.2.6 on 2023-10-22 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_product_sale"),
    ]

    operations = [
        migrations.CreateModel(
            name="Option",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="OptionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="display_home",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="display_slider",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="OptionImages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="images/")),
                (
                    "option",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.option",
                    ),
                ),
                (
                    "option_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.optioncategory",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="option",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="products.optioncategory",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.ManyToManyField(blank=True, to="products.optionimages"),
        ),
        migrations.AddField(
            model_name="product",
            name="option_categorys",
            field=models.ManyToManyField(blank=True, to="products.optioncategory"),
        ),
    ]
