# Generated by Django 4.2.6 on 2023-10-22 09:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0003_option_optioncategory_product_display_home_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="OptionImages",
            new_name="OptionImage",
        ),
    ]
