# Generated by Django 4.2.6 on 2023-10-22 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0004_rename_optionimages_optionimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="optionimage",
            name="option_product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.product",
            ),
        ),
        migrations.AddField(
            model_name="optionimage",
            name="slug",
            field=models.SlugField(default="test", max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
