# Generated by Django 4.2.6 on 2023-10-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0005_optionimage_option_product_optionimage_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="optionimage",
            name="name",
            field=models.CharField(default="Temp", max_length=100),
            preserve_default=False,
        ),
    ]
